apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: brxzqa9h9-go
  janus-idp.io/tekton: brxzqa9h9-go
  backstage.io/kubernetes-id: brxzqa9h9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: brxzqa9h9-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
